export { HomePage } from './HomePage'
export { ProjectsPage } from './ProjectsPage'
export { ProjectDetailPage } from './ProjectDetailPage'
export { ServicesPage } from './ServicesPage'
export { AboutPage } from './AboutPage'
export { ContactPage } from './ContactPage'
export { NotFoundPage } from './NotFoundPage'
